#ifndef VERSION_HPP
#define VERSION_HPP

#define TO_STR2(x) #x
#define TO_STR(x) TO_STR2(x)

#define AUTHOR "Andrulewicz Artur"
#define COPYRIGHT_YEAR 2018
#define SERVER_MAJOR_VERSION 1// BIG UPDATE / NEW CONTENT RELEASE
#define SERVER_MINOR_VERSION 0// CASUAL MONTHLY / EVERY TWO/THREE WEEKS UPDATE WITH NEW STUFF TO EACH PATCH
#define SERVER_PATCH_VERSION 0// SMALL UPDATES / BUG FIXES / MINOR CHANGES
#define SERVER_RELEASE_STATE "Pre-Alpha"

#define CLIENT_MAJOR_VERSION 1// BIG UPDATE / NEW CONTENT RELEASE
#define CLIENT_MINOR_VERSION 0// CASUAL MONTHLY / EVERY TWO/THREE WEEKS UPDATE WITH NEW STUFF TO EACH PATCH
#define CLIENT_PATCH_VERSION 0// SMALL UPDATES / BUG FIXES / MINOR CHANGES
#define CLIENT_RELEASE_STATE "Pre-Alpha"
#define CLIENT_VERSION "Version" " " TO_STR(CLIENT_MAJOR_VERSION) "." TO_STR(CLIENT_MINOR_VERSION) "." TO_STR(CLIENT_PATCH_VERSION) " (" CLIENT_RELEASE_STATE ")"

#define SERVER_NAME "Treasuria"
#define SERVER_VERSION "v." TO_STR(SERVER_MAJOR_VERSION) "." TO_STR(SERVER_MINOR_VERSION) "." TO_STR(SERVER_PATCH_VERSION) " (" SERVER_RELEASE_STATE ")"
#define SERVER_COPYRIGHT "Copyright " TO_STR(COPYRIGHT_YEAR) ". " AUTHOR ". " "All rights reserved."


#endif // VERSION_HPP
